name:                attocalc
version:             0.1.0.0
github:              "kasshiy/attocalc"
license:             BSD3
author:              "Kasshi K"
maintainer:          "kasshi.4259.b.b@gmail.com"
copyright:           "2021 Kasshi K"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kasshiy/attocalc#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- attoparsec

library:
  source-dirs: src

executables:
  attocalc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attocalc
    - optparse-applicative

tests:
  attocalc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attocalc
